# Generated by Django 4.0 on 2022-01-12 01:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tc', '0002_alter_phone_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='contact_list',
            field=models.ManyToManyField(blank=True, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
