# Generated by Django 4.0 on 2022-01-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc', '0003_phone_contact_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
    ]
